### ISSUE TITLE
unable to reviewe perms

### ISSUE THREAD

**Issue by electriquo** [Skeletonxf/duplicate-tab#23] opened 2023-11-04 17:03 UTC
the last update has introduced a change in the extension's permissions. as you can see, firefox overflow menu indicates it with a green dot. yet, was unable to review the perms and take action upon it, which then keeps the green dot on screen. it seems that the permission tab of the extension does list the permissions that are needed like other extensions.

![image](https://github.com/Skeletonxf/duplicate-tab/assets/28758375/96c1d38f-95b8-405f-a67c-2adaf85b3856)

i am using firefox 119.0 (64-bit).

**Comment by Skeletonxf** [comment] 2023-11-04 22:17
Duplicate Tab was updated to manifest version 3 in the last update. As it can only read the user's tab after user interaction I think this is working as intended? The dot goes away for a tab that you interact with the addon on.

I've been annoyed by it too so if this is surprising (ie not seen in other addons) perhaps I've missed something? I'll try to work out what's causing the dot to appear.

**Comment by electriquo** [comment] 2023-11-05 07:47
> if this is surprising (ie not seen in other addons) perhaps I've missed something

it does not appear for other addons even though the interact with the same page. you can test it easily by installing an addon and observe yourself.

maybe it is related to?
> it seems that the permission tab of the extension does list the permissions that are needed like other extensions.

the green dot is problematic, as it indicates that it needs action from the user. when there are other addons besides duplicate-tab, the user cannot tell whether the green dot is from the duplicate-tab or from other addons.

thank you for the addon and hope it'll be fixed soon.

**Comment by Skeletonxf** [comment] 2023-11-05 10:05
This appears to be either a poorly designed feature or a bug in Firefox that I can't fix. https://bugzilla.mozilla.org/show_bug.cgi?id=1851083 https://discourse.mozilla.org/t/permission-needed-indicator-on-browser-action/123183
If you can't cope with the annoying dot then I'd suggest installing version 2.3 https://addons.mozilla.org/en-GB/firefox/addon/duplicate_tab/versions/ and disabling automatic updates so you can stay on the manifest version 2 version that won't have this issue.
I'll leave this issue open until Mozilla fix the annoyance in Firefox or there's a workaround I can do.

**Comment by tuftsanti** [comment] 2023-11-08 16:45
Just wanted to chime in to echo how strange this is. I understand it's a quirk in FF and there's nothing you can do, I just get the constant notification like I have something I need to interact with. I realize it's not the case, but still awkward.

**Comment by Skeletonxf** [comment] 2024-08-10 18:29
This bug seem to be fixed in Firefox 129 and the extended support release 128 :tada: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1851083

**Closed as completed by Skeletonxf** 2024-08-10 18:29 UTC
